services:
  pcmaintenance-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: bulman22/pcmaintenance-web:latest
    container_name: pcmaintenance-web
    ports:
      - "8034:80"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING:-Host=192.168.0.101;Port=5432;Username=postgres;Password=changeme123456789;Database=postgres}
