using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PcMaintenance.Server.Data;

// Migrări EF Core: se aplică la startup cu Migrate() (nu EnsureCreated()). Connection string din config (env/secrets).
var builder = WebApplication.CreateBuilder(new WebApplicationOptions
{
    Args = args,
    WebRootPath = "dist"
});

// Add services to the container.
builder.Services.AddControllers()
    .AddJsonOptions(o => o.JsonSerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase);

// Configure PostgreSQL
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
builder.Services.AddDbContext<AppDbContext>(options => options.UseNpgsql(connectionString));

// Add CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowVueApp", policy =>
    {
        policy.WithOrigins("https://localhost:59404", "https://localhost:59405", "http://localhost:5173")
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

if (!app.Environment.IsDevelopment())
    app.UseHsts();

app.UseHttpsRedirection();
app.UseCors("AllowVueApp");
app.UseRouting();
app.MapControllers();

// SPA: serve static files from dist (set via WebRootPath)
app.UseDefaultFiles();
app.UseStaticFiles();
app.MapFallbackToFile("index.html");

// Apply EF Core migrations at startup (idempotent; no separate deploy step)
using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var logger = scope.ServiceProvider.GetRequiredService<ILoggerFactory>().CreateLogger("Startup");
    context.Database.Migrate();

    // Fallback: dacă __EFMigrationsHistory spune "up to date" dar tabelul Reviews lipsește (istoric desincronizat), creăm tabelul
    var reviewsExists = context.Database
        .SqlQueryRaw<long>("SELECT COUNT(*) AS \"Value\" FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Reviews'")
        .FirstOrDefault();
    if (reviewsExists == 0)
    {
        logger.LogWarning("Tabela Reviews lipsește după Migrate(); se creează prin fallback (istoric EF desincronizat față de schema reală).");
        context.Database.ExecuteSqlRaw("""
            CREATE TABLE "Reviews" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "AuthorName" character varying(200) NOT NULL,
                "Rating" integer NOT NULL,
                "Comment" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            """);
        var historyExists = context.Database
            .SqlQueryRaw<long>("SELECT COUNT(*) AS \"Value\" FROM information_schema.tables WHERE table_schema = 'public' AND table_name = '__EFMigrationsHistory'")
            .FirstOrDefault();
        if (historyExists != 0)
        {
            var migrationRow = context.Database
                .SqlQueryRaw<long>("SELECT COUNT(*) AS \"Value\" FROM \"__EFMigrationsHistory\" WHERE \"MigrationId\" = '20250222000000_InitialCreate'")
                .FirstOrDefault();
            if (migrationRow == 0)
                context.Database.ExecuteSqlRaw("""
                    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
                    VALUES ('20250222000000_InitialCreate', '8.0.11');
                    """);
        }
    }
}

app.Run();
